### ISSUE TITLE
dlinfo missing on Mac OS X

### ISSUE THREAD

**Issue by jdiego** [Manu343726/siplasplas#82]
The "dlinfo" function isn't presented on FreeBSD based system. So, we have to use the dladdr. I made a little patch to add a branch to Mac OS X. If you like and wish we can submit a merge request to your master branch. 

Thanks for your attention. 

Diego
[fix_dynamiclibrary_mac.patch.txt](https://github.com/Manu343726/siplasplas/files/659904/fix_dynamiclibrary_mac.patch.txt)

**Comment by Manu343726** [comment]
Thanks a lot for this
